name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  push:
    branches:
      - 'main'
jobs:
  run-tests:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff
      - uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod
      - name: Show System
        run: |
          uname -a
          just sysinfo
      - name: Run Go Test
        run: |
          just init tidy lint tests
